https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm

In [ ]:
###Módulo de alineamiento global por programación dinámica
import numpy as np

seq1 = "GCATGCU"
seq2 = "GATTACA"

def RecorriendoMatriz (matriz_dir,seq1,seq2,i,j):
    if matriz_dir[i,j] == 0:
        return "","",0
    if matriz_dir[i,j] == 1:
        x, y,puntos = RecorriendoMatriz(matriz_dir,seq1,seq2,i-1,j-1)
        if seq1[i-1] == seq2[j-1]:
            puntos += 1
        return  x+seq1[i-1] , y+seq2[j-1],puntos
    if matriz_dir[i,j] == 2:
        x, y, puntos = RecorriendoMatriz(matriz_dir,seq1,seq2,i-1,j)
        return x+seq1[i-1] , y+"-",puntos
    if matriz_dir[i,j] == 3:
        x, y, puntos = RecorriendoMatriz(matriz_dir,seq1,seq2,i,j-1)
        return x+"-" , y+seq2[j-1],puntos

def Alineamiento (seq1,seq2,match=1,mismatch=1,gapopen=5,gapext=1):
    filas = len(seq1)
    columnas = len(seq2)
    matriz_num = np.zeros((filas+1,columnas+1))
    matriz_dir = np.zeros((filas+1,columnas+1))

    for i in range(1,filas+1):
        matriz_num[i][0] = -gapopen - (i-1)*gapext
        matriz_dir[i][0] = 2

    for j in range(1,columnas+1):
        matriz_num[0][j] = -gapopen - (j-1)*gapext
        matriz_dir[0][j] = 3


    for i in range (0,filas):
        for j in range (0,columnas):
            if seq1[i] == seq2[j]:
                puntaje = match
            else:
                puntaje = -mismatch
            if matriz_dir[i][j+1] == 2:
                gap2 = gapext
            else:
                gap2 = gapopen
            if matriz_dir[i+1][j] == 3:
                gap3 = gapext
            else:
                gap3 = gapopen
            posibilidades=[matriz_num[i][j]+puntaje,matriz_num[i][j+1]-gap2,matriz_num[i+1][j]-gap3]
            matriz_num[i+1][j+1] = max(posibilidades)
            matriz_dir[i+1][j+1] = posibilidades.index(max(posibilidades))+1
    print (matriz_num)
    print (matriz_dir)
    return RecorriendoMatriz(matriz_dir,seq1,seq2,filas,columnas)

print (Alineamiento(seq1,seq2,1.,1.,1.,0.5))

[[ 0.  -1.  -1.5 -2.  -2.5 -3.  -3.5 -4. ]
 [-1.   1.   0.  -0.5 -1.  -1.5 -2.  -2.5]
 [-1.5  0.   0.  -1.  -1.5 -2.  -0.5 -1.5]
 [-2.  -0.5  1.   0.  -0.5 -0.5 -1.5  0.5]
 [-2.5 -1.   0.   2.   1.   0.  -0.5 -0.5]
 [-3.  -1.5 -0.5  1.   1.   0.  -1.  -1. ]
 [-3.5 -2.5 -1.   0.5  0.   0.   1.   0. ]
 [-4.  -3.  -1.5  0.  -0.5 -1.   0.   0. ]]
[[0. 3. 3. 3. 3. 3. 3. 3.]
 [2. 1. 3. 3. 3. 3. 3. 3.]
 [2. 2. 1. 1. 1. 1. 1. 3.]
 [2. 2. 1. 3. 3. 1. 2. 1.]
 [2. 2. 2. 1. 1. 3. 3. 2.]
 [2. 1. 2. 2. 1. 1. 1. 2.]
 [2. 2. 2. 2. 1. 1. 1. 3.]
 [2. 2. 2. 2. 1. 1. 2. 1.]]
('GCA-TGCU', 'G-ATTACA', 4)
